//Frontend
export const LOGIN_WALLPAPER = 'https://img5.goodfon.com/wallpaper/nbig/e/b2/korovy-stado-priroda-lug.jpg'
export const HOME = '/'
export const LOGIN = '/login'
export const AUCTION_CRUD = '/crear-editar-remate'
export const AUCTION = '/remate'
export const AUCTION_HISTORY = '/remate-historial'
export const CLIENT_CRUD = '/crear-editar-cliente'
export const CLIENT_LIST = '/cliente-listado'
export const PROFILE = '/perfil'
export const PASSWORD_CHANGE = '/password-change'
export const LOCALITIES = '/localidades'
export const CATEGORIES = '/categorias'
export const USERS = '/usuarios'
export const USER_CRUD = '/crear-editar-usuario'

//Backend
export const LOGIN_API = '/login'
export const USER_API = '/user'
export const LOCALITY_API = '/locality'
export const CATEGORY_API = '/category'
export const CLIENT_API = '/client'
export const AUCTION_API = '/auction'
export const AUCTION_BATCHES_API = '/auction-batches'
export const USER_AUCTIONS_API = '/auction-user'